config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "poems#index"
  resources :poems do
    member do
      post :clap
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :poems
end

app/models/poem.rb
# coding: utf-8
class Poem < ApplicationRecord
  validates_length_of :short, is: 4, if: -> {genre == "絕句"}, message: "絕句請輸入四字"
  validates_length_of :short, is: 8, if: -> {genre == "律詩"}, message: "律詩請輸入八字"

  before_create :build_full
  belongs_to :author

  paginates_per 10

  @@url_base = "http://cml11.csie.ntu.edu.tw:8081/"

  def build_full
    @short_simplified = Ropencc.conv('t2s.json', short)
    response = infer_poem_with_heads_and_signal.gsub("\n","")
    self.full = Ropencc.conv('s2t.json', response)
  end

  def serialize
    { id: id, short: short, full: full, created_at: created_at, clap: clap }
  end

  private

  def infer_poem_with_heads_and_random_signal
    uri = URI(@@url_base + 'infer_poem_with_heads_and_random_signal')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = false
    request = Net::HTTP::Post.new(uri.request_uri, {'Content-Type' =>'application/json'})

    request.body = JSON.generate({:heads => @short_simplified})

    response = http.request(request)
    JSON.parse(response.body)["outputs"]
  end

  def infer_poem_with_heads_and_signal
    uri = URI(@@url_base + 'infer_poem_with_heads_and_signal')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = false
    request = Net::HTTP::Post.new(uri.request_uri, {'Content-Type' =>'application/json'})

    request.body = JSON.generate(
      { heads: @short_simplified || "測試資料",
        author: author&.simplified_name || "白居易",
        tones: (genre == "絕句") ? get_tones(20) : get_tones(40),
        "POS": (genre == "絕句") ? get_POS(20) : get_POS(40),
        rhymes: (genre == "絕句") ? get_rhymes(4) : get_rhymes(8),
      })

    response = http.request(request)
    JSON.parse(response.body)["outputs"]
  end

  def get_random_signals
    uri = URI.parse(@@url_base + "get_random_signals")
    http = Net::HTTP.new(uri.host, uri.port)
    result = http.get(uri.request_uri)
    JSON.parse result.body
  end

  ['tones', 'POS', 'rhymes'].each do |phrase|
    define_method("get_#{phrase}") do |length|
      loop do
        hash = get_random_signals
        if hash[phrase].split(" ").length == length
          return hash[phrase]
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/poems_controller.rb
# coding: utf-8
class PoemsController < ApplicationController
  def index
    @poems = Poem.all.order(clap: :desc).page(params[:page])
    @new_poem = Poem.new
    @poem = Poem.find_by(id: params[:id].to_i)
  end

  def show
  end

  def create
    @poem = Poem.new(poem_params)

    if @poem.save
      redirect_to poems_path(id: @poem.id, page: Poem.count / 10 + 1)
    else
      flash[:error] = @poem.errors.map {|attr, error| error}.join("，")
      redirect_to poems_path
    end
  end

  def clap
    @poem = Poem.find(params[:id])
    @poem.clap += 1
    @poem.save
    page = Poem.order(clap: :desc).all.pluck(:id).index(@poem.id) / 10 + 1
    @poems = Poem.all.order(clap: :desc).page(page)
    poems_html = render(template: "poems/_poems_table.html.slim", locals: {poems: @poems}, layout: false)

    ActionCable.server.broadcast 'poem_clap_channel',
                                 {poem: {id: @poem.id, clap: @poem.clap},
                                  poems: poems_html }
  end

  private
  def poem_params
    params.require(:poem).permit(:id, :short, :genre, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poems_helper.rb
# coding: utf-8
module PoemsHelper
  def poem_layout(text = @poem.full,new_line: true)
    text.split("").each_slice(20).map do |slice|
      slice.insert(20, new_line ? "。<br/>" : "。")
      slice.insert(15, "，")
      slice.insert(10, new_line ? "；<br/>" : "；")
      slice.insert(5, "，")
      slice
    end.join
  end
end

app/views/layouts/application.html.slim
html
  head
    title 唐詩生成 | SDML Final Project
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag

  body.l-body
    .container
      = yield

app/views/poems/_poem.html.slim
tr
  td = poem.short
  td = poem_layout(poem.full, new_line: false)
  td = poem.created_at.to_s(:short)
  td.poem-clap class="poem-#{poem.id}-clap" = poem.clap
  td = button_to "clap", clap_poem_path(poem), class: "btn btn-outline-dark btn-sm", remote: true, method: :post

app/views/poems/_poems_table.html.slim
table.table
  thead
    tr
      td 藏頭
      td 全文
      td 生成時間
      td 掌聲
      td
      tbody = render partial: "poem", collection: poems, as: :poem
= paginate poems, params: {controller: 'poems', action: "index"}

app/views/poems/index.html.slim
- flash.each do |k, v|
 = content_tag(:div, class: "alert alert-danger fade show") do
   = v
.jumbotron
  h1 唐詩生成
  p
    = "Final Project of "
    = link_to('Special Direction on Machine Learning, 2018 Fall', 'https://www.csie.ntu.edu.tw/~sdlin/Courses/SDML.htm')
  h6 組員（羅馬字母序）
  p 張雅量 Chang, Ya-Liang / 陳家陞 Chen, Chia-Sheng / 林俊辰 Lin, Chun-Chen
.row
  .col-12.col-lg-6
    h1 輸入藏頭
    = form_for @new_poem, url: {action: "create"} do |f|
      .form-group
        label 絕句 / 律詩
        = f.select :genre, ["絕句","律詩"], {}, {class: "form-control"}
      .form-group
        label 作者風格
        = f.collection_select :author_id, Author.all.order(amount: :desc), :id, :name, {}, {class: "form-control"}
      .form-group
        label 藏頭句子
        small = " 絕句請輸入四字，律詩請輸入八字"
        = f.text_field :short,  class: "form-control"
      = f.submit "送出", class: "btn btn-primary"

  .col-12.col-lg-6
    - if @poem
      h1 生成結果
      p = raw poem_layout

.row
  .col-12
    h1 排行榜
    #poem-rank = render partial: "poems_table", locals: {poems: @poems}